import 'package:flutter/cupertino.dart';
import 'package:flutter_iconly/widgets/iconly_bold.dart';
import 'package:flutter_iconly/widgets/iconly_broken.dart';
import 'package:flutter_iconly/widgets/iconly_light_outline.dart';

class Constants {
  static List iconlyData = [iconlyLightData, iconlyBoldData, iconlyBrokenData];

  static List<IconlyData> iconlyLightData = [
    IconlyData(iconName: 'user2', iconData: IconlyLight.user2),
    IconlyData(iconName: 'user3', iconData: IconlyLight.user3),
    IconlyData(iconName: 'activity', iconData: IconlyLight.activity),
    IconlyData(iconName: 'addUser', iconData: IconlyLight.addUser),
    IconlyData(iconName: 'arrowDown2', iconData: IconlyLight.arrowDown2),
    IconlyData(iconName: 'arrowDown3', iconData: IconlyLight.arrowDown3),
    IconlyData(
        iconName: 'arrowDownCircle', iconData: IconlyLight.arrowDownCircle),
    IconlyData(
        iconName: 'arrowDownSquare', iconData: IconlyLight.arrowDownSquare),
    IconlyData(iconName: 'arrowDown', iconData: IconlyLight.arrowDown),
    IconlyData(iconName: 'arrowLeft2', iconData: IconlyLight.arrowLeft2),
    IconlyData(iconName: 'arrowLeft3', iconData: IconlyLight.arrowLeft3),
    IconlyData(
        iconName: 'arrowLeftCircle', iconData: IconlyLight.arrowLeftCircle),
    IconlyData(
        iconName: 'arrowLeftSquare', iconData: IconlyLight.arrowLeftSquare),
    IconlyData(iconName: 'arrowLeft', iconData: IconlyLight.arrowLeft),
    IconlyData(iconName: 'arrowRight2', iconData: IconlyLight.arrowRight2),
    IconlyData(iconName: 'arrowRight3', iconData: IconlyLight.arrowRight3),
    IconlyData(
        iconName: 'arrowRightCircle', iconData: IconlyLight.arrowRightCircle),
    IconlyData(
        iconName: 'arrowRightSquare', iconData: IconlyLight.arrowRightSquare),
    IconlyData(iconName: 'arrowRight', iconData: IconlyLight.arrowRight),
    IconlyData(iconName: 'arrowUp2', iconData: IconlyLight.arrowUp2),
    IconlyData(iconName: 'arrowUp3', iconData: IconlyLight.arrowUp3),
    IconlyData(iconName: 'arrowUpCircle', iconData: IconlyLight.arrowUpCircle),
    IconlyData(iconName: 'arrowUpSquare', iconData: IconlyLight.arrowUpSquare),
    IconlyData(iconName: 'arrowUp', iconData: IconlyLight.arrowUp),
    IconlyData(iconName: 'bag2', iconData: IconlyLight.bag2),
    IconlyData(iconName: 'bag', iconData: IconlyLight.bag),
    IconlyData(iconName: 'bookmark', iconData: IconlyLight.bookmark),
    IconlyData(iconName: 'buy', iconData: IconlyLight.buy),
    IconlyData(iconName: 'calendar', iconData: IconlyLight.calendar),
    IconlyData(iconName: 'callMissed', iconData: IconlyLight.callMissed),
    IconlyData(iconName: 'callSilent', iconData: IconlyLight.callSilent),
    IconlyData(iconName: 'call', iconData: IconlyLight.call),
    IconlyData(iconName: 'calling', iconData: IconlyLight.calling),
    IconlyData(iconName: 'camera', iconData: IconlyLight.camera),
    IconlyData(iconName: 'category', iconData: IconlyLight.category),
    IconlyData(iconName: 'chart', iconData: IconlyLight.chart),
    IconlyData(iconName: 'chat', iconData: IconlyLight.chat),
    IconlyData(iconName: 'closeSquare', iconData: IconlyLight.closeSquare),
    IconlyData(iconName: 'dangerCircle', iconData: IconlyLight.dangerCircle),
    IconlyData(
        iconName: 'dangerTriangle', iconData: IconlyLight.dangerTriangle),
    IconlyData(iconName: 'delete', iconData: IconlyLight.delete),
    IconlyData(iconName: 'discount', iconData: IconlyLight.discount),
    IconlyData(iconName: 'discovery', iconData: IconlyLight.discovery),
    IconlyData(iconName: 'document', iconData: IconlyLight.document),
    IconlyData(iconName: 'download', iconData: IconlyLight.download),
    IconlyData(iconName: 'editSquare', iconData: IconlyLight.editSquare),
    IconlyData(iconName: 'edit', iconData: IconlyLight.edit),
    IconlyData(iconName: 'filter2', iconData: IconlyLight.filter2),
    IconlyData(iconName: 'filter', iconData: IconlyLight.filter),
    IconlyData(iconName: 'folder', iconData: IconlyLight.folder),
    IconlyData(iconName: 'game', iconData: IconlyLight.game),
    IconlyData(iconName: 'graph', iconData: IconlyLight.graph),
    IconlyData(iconName: 'heart', iconData: IconlyLight.heart),
    IconlyData(iconName: 'hide', iconData: IconlyLight.hide),
    IconlyData(iconName: 'home', iconData: IconlyLight.home),
    IconlyData(iconName: 'image2', iconData: IconlyLight.image2),
    IconlyData(iconName: 'image', iconData: IconlyLight.image),
    IconlyData(iconName: 'infoSquare', iconData: IconlyLight.infoSquare),
    IconlyData(iconName: 'location', iconData: IconlyLight.location),
    IconlyData(iconName: 'lock', iconData: IconlyLight.lock),
    IconlyData(iconName: 'login', iconData: IconlyLight.login),
    IconlyData(iconName: 'logout', iconData: IconlyLight.logout),
    IconlyData(iconName: 'message', iconData: IconlyLight.message),
    IconlyData(iconName: 'moreCircle', iconData: IconlyLight.moreCircle),
    IconlyData(iconName: 'moreSquare', iconData: IconlyLight.moreSquare),
    IconlyData(iconName: 'notification', iconData: IconlyLight.notification),
    IconlyData(iconName: 'paperDownload', iconData: IconlyLight.paperDownload),
    IconlyData(iconName: 'paperFail', iconData: IconlyLight.paperFail),
    IconlyData(iconName: 'paperNegative', iconData: IconlyLight.paperNegative),
    IconlyData(iconName: 'paperPlus', iconData: IconlyLight.paperPlus),
    IconlyData(iconName: 'paperUpload', iconData: IconlyLight.paperUpload),
    IconlyData(iconName: 'paper', iconData: IconlyLight.paper),
    IconlyData(iconName: 'password', iconData: IconlyLight.password),
    IconlyData(iconName: 'play', iconData: IconlyLight.play),
    IconlyData(iconName: 'plus', iconData: IconlyLight.plus),
    IconlyData(iconName: 'profile', iconData: IconlyLight.profile),
    IconlyData(iconName: 'scan', iconData: IconlyLight.scan),
    IconlyData(iconName: 'search', iconData: IconlyLight.search),
    IconlyData(iconName: 'send', iconData: IconlyLight.send),
    IconlyData(iconName: 'setting', iconData: IconlyLight.setting),
    IconlyData(iconName: 'shieldDone', iconData: IconlyLight.shieldDone),
    IconlyData(iconName: 'shieldFail', iconData: IconlyLight.shieldFail),
    IconlyData(iconName: 'show', iconData: IconlyLight.show),
    IconlyData(iconName: 'star', iconData: IconlyLight.star),
    IconlyData(iconName: 'swap', iconData: IconlyLight.swap),
    IconlyData(iconName: 'tickSquare', iconData: IconlyLight.tickSquare),
    IconlyData(iconName: 'ticketStar', iconData: IconlyLight.ticketStar),
    IconlyData(iconName: 'ticket', iconData: IconlyLight.ticket),
    IconlyData(iconName: 'timeCircle', iconData: IconlyLight.timeCircle),
    IconlyData(iconName: 'timeSquare', iconData: IconlyLight.timeSquare),
    IconlyData(iconName: 'unlock', iconData: IconlyLight.unlock),
    IconlyData(iconName: 'upload', iconData: IconlyLight.upload),
    IconlyData(iconName: 'video', iconData: IconlyLight.video),
    IconlyData(iconName: 'voice2', iconData: IconlyLight.voice2),
    IconlyData(iconName: 'voice', iconData: IconlyLight.voice),
    IconlyData(iconName: 'volumeDown', iconData: IconlyLight.volumeDown),
    IconlyData(iconName: 'volumeOff', iconData: IconlyLight.volumeOff),
    IconlyData(iconName: 'volumeUp', iconData: IconlyLight.volumeUp),
    IconlyData(iconName: 'wallet', iconData: IconlyLight.wallet),
    IconlyData(iconName: 'work', iconData: IconlyLight.work),
  ];

  static List<IconlyData> iconlyBoldData = [
    IconlyData(iconName: 'user2', iconData: IconlyBold.user2),
    IconlyData(iconName: 'user3', iconData: IconlyBold.user3),
    IconlyData(iconName: 'activity', iconData: IconlyBold.activity),
    IconlyData(iconName: 'addUser', iconData: IconlyBold.addUser),
    IconlyData(iconName: 'arrowDown2', iconData: IconlyBold.arrowDown2),
    IconlyData(iconName: 'arrowDown3', iconData: IconlyBold.arrowDown3),
    IconlyData(
        iconName: 'arrowDownCircle', iconData: IconlyBold.arrowDownCircle),
    IconlyData(
        iconName: 'arrowDownSquare', iconData: IconlyBold.arrowDownSquare),
    IconlyData(iconName: 'arrowDown', iconData: IconlyBold.arrowDown),
    IconlyData(iconName: 'arrowLeft2', iconData: IconlyBold.arrowLeft2),
    IconlyData(iconName: 'arrowLeft3', iconData: IconlyBold.arrowLeft3),
    IconlyData(
        iconName: 'arrowLeftCircle', iconData: IconlyBold.arrowLeftCircle),
    IconlyData(
        iconName: 'arrowLeftSquare', iconData: IconlyBold.arrowLeftSquare),
    IconlyData(iconName: 'arrowLeft', iconData: IconlyBold.arrowLeft),
    IconlyData(iconName: 'arrowRight2', iconData: IconlyBold.arrowRight2),
    IconlyData(iconName: 'arrowRight3', iconData: IconlyBold.arrowRight3),
    IconlyData(
        iconName: 'arrowRightCircle', iconData: IconlyBold.arrowRightCircle),
    IconlyData(
        iconName: 'arrowRightSquare', iconData: IconlyBold.arrowRightSquare),
    IconlyData(iconName: 'arrowRight', iconData: IconlyBold.arrowRight),
    IconlyData(iconName: 'arrowUp2', iconData: IconlyBold.arrowUp2),
    IconlyData(iconName: 'arrowUp3', iconData: IconlyBold.arrowUp3),
    IconlyData(iconName: 'arrowUpCircle', iconData: IconlyBold.arrowUpCircle),
    IconlyData(iconName: 'arrowUpSquare', iconData: IconlyBold.arrowUpSquare),
    IconlyData(iconName: 'arrowUp', iconData: IconlyBold.arrowUp),
    IconlyData(iconName: 'bag2', iconData: IconlyBold.bag2),
    IconlyData(iconName: 'bag', iconData: IconlyBold.bag),
    IconlyData(iconName: 'bookmark', iconData: IconlyBold.bookmark),
    IconlyData(iconName: 'buy', iconData: IconlyBold.buy),
    IconlyData(iconName: 'calendar', iconData: IconlyBold.calendar),
    IconlyData(iconName: 'callMissed', iconData: IconlyBold.callMissed),
    IconlyData(iconName: 'callSilent', iconData: IconlyBold.callSilent),
    IconlyData(iconName: 'call', iconData: IconlyBold.call),
    IconlyData(iconName: 'calling', iconData: IconlyBold.calling),
    IconlyData(iconName: 'camera', iconData: IconlyBold.camera),
    IconlyData(iconName: 'category', iconData: IconlyBold.category),
    IconlyData(iconName: 'chart', iconData: IconlyBold.chart),
    IconlyData(iconName: 'chat', iconData: IconlyBold.chat),
    IconlyData(iconName: 'closeSquare', iconData: IconlyBold.closeSquare),
    IconlyData(iconName: 'danger', iconData: IconlyBold.danger),
    IconlyData(iconName: 'delete', iconData: IconlyBold.delete),
    IconlyData(iconName: 'discount', iconData: IconlyBold.discount),
    IconlyData(iconName: 'discovery', iconData: IconlyBold.discovery),
    IconlyData(iconName: 'document', iconData: IconlyBold.document),
    IconlyData(iconName: 'download', iconData: IconlyBold.download),
    IconlyData(iconName: 'editSquare', iconData: IconlyBold.editSquare),
    IconlyData(iconName: 'edit', iconData: IconlyBold.edit),
    IconlyData(iconName: 'filter2', iconData: IconlyBold.filter2),
    IconlyData(iconName: 'filter', iconData: IconlyBold.filter),
    IconlyData(iconName: 'folder', iconData: IconlyBold.folder),
    IconlyData(iconName: 'game', iconData: IconlyBold.game),
    IconlyData(iconName: 'graph', iconData: IconlyBold.graph),
    IconlyData(iconName: 'heart', iconData: IconlyBold.heart),
    IconlyData(iconName: 'hide', iconData: IconlyBold.hide),
    IconlyData(iconName: 'home', iconData: IconlyBold.home),
    IconlyData(iconName: 'image2', iconData: IconlyBold.image2),
    IconlyData(iconName: 'image', iconData: IconlyBold.image),
    IconlyData(iconName: 'infoCircle', iconData: IconlyBold.infoCircle),
    IconlyData(iconName: 'infoSquare', iconData: IconlyBold.infoSquare),
    IconlyData(iconName: 'location', iconData: IconlyBold.location),
    IconlyData(iconName: 'lock', iconData: IconlyBold.lock),
    IconlyData(iconName: 'login', iconData: IconlyBold.login),
    IconlyData(iconName: 'logout', iconData: IconlyBold.logout),
    IconlyData(iconName: 'message', iconData: IconlyBold.message),
    IconlyData(iconName: 'moreCircle', iconData: IconlyBold.moreCircle),
    IconlyData(iconName: 'moreSquare', iconData: IconlyBold.moreSquare),
    IconlyData(iconName: 'notification', iconData: IconlyBold.notification),
    IconlyData(iconName: 'paperDownload', iconData: IconlyBold.paperDownload),
    IconlyData(iconName: 'paperFail', iconData: IconlyBold.paperFail),
    IconlyData(iconName: 'paperNegative', iconData: IconlyBold.paperNegative),
    IconlyData(iconName: 'paperPlus', iconData: IconlyBold.paperPlus),
    IconlyData(iconName: 'paperUpload', iconData: IconlyBold.paperUpload),
    IconlyData(iconName: 'paper', iconData: IconlyBold.paper),
    IconlyData(iconName: 'password', iconData: IconlyBold.password),
    IconlyData(iconName: 'play', iconData: IconlyBold.play),
    IconlyData(iconName: 'plus', iconData: IconlyBold.plus),
    IconlyData(iconName: 'profile', iconData: IconlyBold.profile),
    IconlyData(iconName: 'scan', iconData: IconlyBold.scan),
    IconlyData(iconName: 'search', iconData: IconlyBold.search),
    IconlyData(iconName: 'send', iconData: IconlyBold.send),
    IconlyData(iconName: 'setting', iconData: IconlyBold.setting),
    IconlyData(iconName: 'shieldDone', iconData: IconlyBold.shieldDone),
    IconlyData(iconName: 'shieldFail', iconData: IconlyBold.shieldFail),
    IconlyData(iconName: 'show', iconData: IconlyBold.show),
    IconlyData(iconName: 'star', iconData: IconlyBold.star),
    IconlyData(iconName: 'swap', iconData: IconlyBold.swap),
    IconlyData(iconName: 'tickSquare', iconData: IconlyBold.tickSquare),
    IconlyData(iconName: 'ticketStar', iconData: IconlyBold.ticketStar),
    IconlyData(iconName: 'ticket', iconData: IconlyBold.ticket),
    IconlyData(iconName: 'timeCircle', iconData: IconlyBold.timeCircle),
    IconlyData(iconName: 'timeSquare', iconData: IconlyBold.timeSquare),
    IconlyData(iconName: 'unlock', iconData: IconlyBold.unlock),
    IconlyData(iconName: 'upload', iconData: IconlyBold.upload),
    IconlyData(iconName: 'video', iconData: IconlyBold.video),
    IconlyData(iconName: 'voice2', iconData: IconlyBold.voice2),
    IconlyData(iconName: 'voice', iconData: IconlyBold.voice),
    IconlyData(iconName: 'volumeDown', iconData: IconlyBold.volumeDown),
    IconlyData(iconName: 'volumeOff', iconData: IconlyBold.volumeOff),
    IconlyData(iconName: 'volumeUp', iconData: IconlyBold.volumeUp),
    IconlyData(iconName: 'wallet', iconData: IconlyBold.wallet),
    IconlyData(iconName: 'work', iconData: IconlyBold.work),
  ];

  static List<IconlyData> iconlyBrokenData = [
    IconlyData(iconName: 'user2', iconData: IconlyBroken.user2),
    IconlyData(iconName: 'user3', iconData: IconlyBroken.user3),
    IconlyData(iconName: 'activity', iconData: IconlyBroken.activity),
    IconlyData(iconName: 'addUser', iconData: IconlyBroken.addUser),
    IconlyData(iconName: 'arrowDown2', iconData: IconlyBroken.arrowDown2),
    IconlyData(iconName: 'arrowDown3', iconData: IconlyBroken.arrowDown3),
    IconlyData(
        iconName: 'arrowDownCircle', iconData: IconlyBroken.arrowDownCircle),
    IconlyData(
        iconName: 'arrowDownSquare', iconData: IconlyBroken.arrowDownSquare),
    IconlyData(iconName: 'arrowDown', iconData: IconlyBroken.arrowDown),
    IconlyData(iconName: 'arrowLeft2', iconData: IconlyBroken.arrowLeft2),
    IconlyData(iconName: 'arrowLeft3', iconData: IconlyBroken.arrowLeft3),
    IconlyData(
        iconName: 'arrowLeftCircle', iconData: IconlyBroken.arrowLeftCircle),
    IconlyData(
        iconName: 'arrowLeftSquare', iconData: IconlyBroken.arrowLeftSquare),
    IconlyData(iconName: 'arrowLeft', iconData: IconlyBroken.arrowLeft),
    IconlyData(iconName: 'arrowRight2', iconData: IconlyBroken.arrowRight2),
    IconlyData(iconName: 'arrowRight3', iconData: IconlyBroken.arrowRight3),
    IconlyData(
        iconName: 'arrowRightCircle', iconData: IconlyBroken.arrowRightCircle),
    IconlyData(
        iconName: 'arrowRightSquare', iconData: IconlyBroken.arrowRightSquare),
    IconlyData(iconName: 'arrowRight', iconData: IconlyBroken.arrowRight),
    IconlyData(iconName: 'arrowUp2', iconData: IconlyBroken.arrowUp2),
    IconlyData(iconName: 'arrowUp3', iconData: IconlyBroken.arrowUp3),
    IconlyData(iconName: 'arrowUpCircle', iconData: IconlyBroken.arrowUpCircle),
    IconlyData(iconName: 'arrowUpSquare', iconData: IconlyBroken.arrowUpSquare),
    IconlyData(iconName: 'arrowUp', iconData: IconlyBroken.arrowUp),
    IconlyData(iconName: 'bag2', iconData: IconlyBroken.bag2),
    IconlyData(iconName: 'bag', iconData: IconlyBroken.bag),
    IconlyData(iconName: 'bookmark', iconData: IconlyBroken.bookmark),
    IconlyData(iconName: 'buy', iconData: IconlyBroken.buy),
    IconlyData(iconName: 'calendar', iconData: IconlyBroken.calendar),
    IconlyData(iconName: 'callMissed', iconData: IconlyBroken.callMissed),
    IconlyData(iconName: 'callSilent', iconData: IconlyBroken.callSilent),
    IconlyData(iconName: 'call', iconData: IconlyBroken.call),
    IconlyData(iconName: 'calling', iconData: IconlyBroken.calling),
    IconlyData(iconName: 'camera', iconData: IconlyBroken.camera),
    IconlyData(iconName: 'category', iconData: IconlyBroken.category),
    IconlyData(iconName: 'chart', iconData: IconlyBroken.chart),
    IconlyData(iconName: 'chat', iconData: IconlyBroken.chat),
    IconlyData(iconName: 'closeSquare', iconData: IconlyBroken.closeSquare),
    IconlyData(iconName: 'danger', iconData: IconlyBroken.danger),
    IconlyData(iconName: 'delete', iconData: IconlyBroken.delete),
    IconlyData(iconName: 'discount', iconData: IconlyBroken.discount),
    IconlyData(iconName: 'discovery', iconData: IconlyBroken.discovery),
    IconlyData(iconName: 'document', iconData: IconlyBroken.document),
    IconlyData(iconName: 'download', iconData: IconlyBroken.download),
    IconlyData(iconName: 'editSquare', iconData: IconlyBroken.editSquare),
    IconlyData(iconName: 'edit', iconData: IconlyBroken.edit),
    IconlyData(iconName: 'filter2', iconData: IconlyBroken.filter2),
    IconlyData(iconName: 'filter', iconData: IconlyBroken.filter),
    IconlyData(iconName: 'folder', iconData: IconlyBroken.folder),
    IconlyData(iconName: 'game', iconData: IconlyBroken.game),
    IconlyData(iconName: 'graph', iconData: IconlyBroken.graph),
    IconlyData(iconName: 'heart', iconData: IconlyBroken.heart),
    IconlyData(iconName: 'hide', iconData: IconlyBroken.hide),
    IconlyData(iconName: 'home', iconData: IconlyBroken.home),
    IconlyData(iconName: 'image2', iconData: IconlyBroken.image2),
    IconlyData(iconName: 'image', iconData: IconlyBroken.image),
    IconlyData(iconName: 'infoCircle', iconData: IconlyBroken.infoCircle),
    IconlyData(iconName: 'infoSquare', iconData: IconlyBroken.infoSquare),
    IconlyData(iconName: 'location', iconData: IconlyBroken.location),
    IconlyData(iconName: 'lock', iconData: IconlyBroken.lock),
    IconlyData(iconName: 'login', iconData: IconlyBroken.login),
    IconlyData(iconName: 'logout', iconData: IconlyBroken.logout),
    IconlyData(iconName: 'message', iconData: IconlyBroken.message),
    IconlyData(iconName: 'moreCircle', iconData: IconlyBroken.moreCircle),
    IconlyData(iconName: 'moreSquare', iconData: IconlyBroken.moreSquare),
    IconlyData(iconName: 'notification', iconData: IconlyBroken.notification),
    IconlyData(iconName: 'paperDownload', iconData: IconlyBroken.paperDownload),
    IconlyData(iconName: 'paperFail', iconData: IconlyBroken.paperFail),
    IconlyData(iconName: 'paperNegative', iconData: IconlyBroken.paperNegative),
    IconlyData(iconName: 'paperPlus', iconData: IconlyBroken.paperPlus),
    IconlyData(iconName: 'paperUpload', iconData: IconlyBroken.paperUpload),
    IconlyData(iconName: 'paper', iconData: IconlyBroken.paper),
    IconlyData(iconName: 'password', iconData: IconlyBroken.password),
    IconlyData(iconName: 'play', iconData: IconlyBroken.play),
    IconlyData(iconName: 'plus', iconData: IconlyBroken.plus),
    IconlyData(iconName: 'profile', iconData: IconlyBroken.profile),
    IconlyData(iconName: 'scan', iconData: IconlyBroken.scan),
    IconlyData(iconName: 'search', iconData: IconlyBroken.search),
    IconlyData(iconName: 'send', iconData: IconlyBroken.send),
    IconlyData(iconName: 'setting', iconData: IconlyBroken.setting),
    IconlyData(iconName: 'shieldDone', iconData: IconlyBroken.shieldDone),
    IconlyData(iconName: 'shieldFail', iconData: IconlyBroken.shieldFail),
    IconlyData(iconName: 'show', iconData: IconlyBroken.show),
    IconlyData(iconName: 'star', iconData: IconlyBroken.star),
    IconlyData(iconName: 'swap', iconData: IconlyBroken.swap),
    IconlyData(iconName: 'tickSquare', iconData: IconlyBroken.tickSquare),
    IconlyData(iconName: 'ticketStar', iconData: IconlyBroken.ticketStar),
    IconlyData(iconName: 'ticket', iconData: IconlyBroken.ticket),
    IconlyData(iconName: 'timeCircle', iconData: IconlyBroken.timeCircle),
    IconlyData(iconName: 'timeSquare', iconData: IconlyBroken.timeSquare),
    IconlyData(iconName: 'unlock', iconData: IconlyBroken.unlock),
    IconlyData(iconName: 'upload', iconData: IconlyBroken.upload),
    IconlyData(iconName: 'video', iconData: IconlyBroken.video),
    IconlyData(iconName: 'voice2', iconData: IconlyBroken.voice2),
    IconlyData(iconName: 'voice', iconData: IconlyBroken.voice),
    IconlyData(iconName: 'volumeDown', iconData: IconlyBroken.volumeDown),
    IconlyData(iconName: 'volumeOff', iconData: IconlyBroken.volumeOff),
    IconlyData(iconName: 'volumeUp', iconData: IconlyBroken.volumeUp),
    IconlyData(iconName: 'wallet', iconData: IconlyBroken.wallet),
    IconlyData(iconName: 'work', iconData: IconlyBroken.work),
  ];
}

class IconlyData {
  final String iconName;
  final IconData iconData;

  IconlyData({
    required this.iconName,
    required this.iconData,
  });
}
